image: python

stages:
- build
- test
- deploy

build-job:
stage: build
script:
- python3 -V

test-cout:
stage: test
script:
- python3 [sum.py](http://sum.py/)

deploy-job:
stage: deploy
script:
- echo "Termiou :)"
